site_name: "Aishwarya Jauhari Sharma"
site_description: "AI/ML Engineer | MLOps & GenAI Enthusiast | Data-Driven Thinker - Production-grade AI/ML projects showcasing MLOps, GenAI, and modern development practices"
site_author: "Aishwarya Jauhari Sharma"
site_url: "https://aishwaryaj7.github.io"

# Repository
repo_name: "aishwaryaj7/aishwaryaj7.github.io"
repo_url: "https://github.com/aishwaryaj7/aishwaryaj7.github.io"
edit_uri: "edit/main/docs/"

# Configuration
theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Inter
    code: JetBrains Mono
  favicon: assets/images/favicon.svg
  logo: assets/images/logo.svg
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    logo: material/account-circle

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Custom CSS and JavaScript
extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mermaid2

# Custom CSS for personal pages
extra_css:
  - stylesheets/extra.css

# Navigation
nav:
  - Home: index.md
  - Projects:
    - Overview: projects/index.md
    - Energy Price Forecasting: projects/energy-price-forecasting/index.md
    - DocTract - Document RAG Assistant: projects/doctract/index.md
    - Doc Parser - PDF Processing: projects/doc-parser/index.md
    - Speech2Text - Audio Transcription: projects/speech2text/index.md
  - Blog:
    - Latest Posts: blog/index.md
    - AI Architecture & Integration:
        - "Understanding Model Context Protocol (MCP): The Future of AI Tool Integration": blog/mcp-deep-dive.md
    - MLOps Series:
      - "Building an End-to-End MLOps Pipeline: Predicting Electricity Prices": blog/energy-price-forecasting-mlops.md
    - AI & Document Processing:
      - "Building DocTract: My Journey into RAG and Local AI": blog/doctract-rag-journey.md
      - "Speech Recognition Made Simple: My HuggingFace Journey": blog/speech2text-journey.md
  - Resume: resume.md
  - Contact: contact.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aishwaryaj7
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aishwarya-jauhari/
      name: LinkedIn
    - icon: fontawesome/solid/envelope
      link: mailto:aishwarya.jauhari@icloud.com
      name: Email
  generator: false

# Copyright
copyright: >
  Copyright &copy; 2025 Aishwarya Jauhari Sharma •
  Built with <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank" rel="noopener">Material for MkDocs</a>


